### ISSUE TITLE
path may not be null or empty string. path='null'

### ISSUE THREAD

**Issue by Alexwsc** [deven98/MetaFlutter#12]
* Error running Gradle:
ProcessException: Process "E:\FlutterProjects\MetaFlutter-1.1\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file 'E:\FlutterProjects\MetaFlutter-1.1\android\app\build.gradle' line: 54

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path='null'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
  Command: E:\FlutterProjects\MetaFlutter-1.1\android\gradlew.bat app:properties

i think that the keystoreProperties is not founded

**Comment by d3xvn** [comment]
Checkout #6 for a solution to this

**Comment by Alexwsc** [comment]
yes,thanks
