### ISSUE TITLE
Gradle issue 

### ISSUE THREAD

**Issue by Fethi-Hamdani** [deven98/MetaFlutter#6]
i can't run the app.
any suggestions
BUILD FAILED in 1s
  Command: /root/Documents/MetaFlutter-master/android/gradlew app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by sherlockbeard** [comment]
go to gradle and comment out signed key files .

**Comment by d3xvn** [comment]
Hi, in the android/app/build.gradle please comment out these lines:

```
    keyAlias keystoreProperties['keyAlias']
    keyPassword keystoreProperties['keyPassword']
    storeFile file(keystoreProperties['storeFile'])
    storePassword keystoreProperties['storePassword']
```

I'm aware of this being on the master branch, will comment out soon.

**Comment by Fethi-Hamdani** [comment]
thanks guys that solved it, i just added border radius to a container and it is working pretty fine i'll try to add some other design features.
